### ISSUE TITLE
the name of the folder must match the project name in your .cabal

### ISSUE THREAD

**Issue by rvion** [Globidev/Twitch-hs#6]
Stack team fixed the bug with stack-ide yesterday, but this morning, I still had some trouble to get it work. Turns out the name of the project 'twich-hs' (defined in your .cabal) must be the same as the folder name

**Comment by rvion** [comment]
then you'll have some nice:
![image](https://cloud.githubusercontent.com/assets/2150990/9288530/cd39b45c-434a-11e5-8686-4645d1f97a4b.png)

**Comment by Globidev** [comment]
done in @eb10949157533298ea0ac38367ee8c350daf918e
