### ISSUE TITLE
automate C compiling 

### ISSUE THREAD

**Issue by rvion** [Globidev/Twitch-hs#8]
Library foobar
  -- ...
  -- The C source files to compile, in that order
  C-sources: cbits/foobar.c, cbits/foobaz.c
  -- The location of the header files
  Include-dirs: include
  -- The header files to be included
  Includes: foobar.h, foobaz.h
  -- Header files to install
  Install-includes: foobar.h, foobaz.h

**Comment by Globidev** [comment]
Fixed in 5f9524a9b2f70ae799fa48dfd1964a4a4fd833cd
